<?php

use Drupal\Core\Field\FieldItemListInterface;

/**
 * Implements hook_locale_translation_projects_alter().
 */
function styles_locale_translation_projects_alter(&$projects) {
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('styles')->getPath();
  $projects['styles']['info']['interface translation server pattern']
    = $path . '/translations/%language.po';
}

/**
 * Implements hook_rebuild().
 */
function styles_rebuild() {
  /** @var \Drupal\styles\StylesManager $stylesManager */
  $stylesManager = \Drupal::service('styles.manager');
  $stylesManager->rebuild();
}

/**
 * Implements hook_theme().
 */
function styles_theme() {
  return [
    'styles_preview' => [
      'render element' => 'elements',
    ],
    'styles_preview__button' => [
      'base hook' => 'styles_preview'
    ],
    'styles_preview__text' => [
      'base hook' => 'styles_preview'
    ],
    'styles_preview__object' => [
      'base hook' => 'styles_preview'
    ],
    'styles_preview__icon' => [
      'base hook' => 'styles_preview'
    ]
  ];
}

function template_preprocess_styles_preview(&$variables) {
  $variables['style'] = $variables['elements']['#style'] ?? '';
  $variables['title'] = $variables['elements']['#title'] ?? '';
  $variables['collection'] = $variables['elements']['#collection'] ?? '';
  $variables['form_item_id'] = $variables['elements']['#form_item_id'] ?? '';
  $variables['active'] = $variables['elements']['#active'] ?? FALSE;
  $variables['toggle'] = $variables['elements']['#toggle'] ?? FALSE;

  /** @var \Drupal\styles\StylesManager $stylesManager */
  $stylesManager = \Drupal::service('styles.manager');
  $collection = $stylesManager->getCollection($variables['collection']);
  $style = $variables['style'];

  if (empty($style)) {
    $variables['title'] = t('- None -');
  } else {
    $variables['title'] = t($collection->getStyles()[$style]);
  }
  $variables['preview_type'] = $variables['elements']['#preview_type'] ?? $collection->getPreviewStyle();
  $variables['#attached']['library'] = array_merge($variables['#attached']['library'] ?? [], $collection->getLibraries(TRUE));
  $variables['attributes']['data-widget'] = $variables['form_item_id'];
  $variables['attributes']['data-style'] = $style;
  $variables['attributes']['class'] = $collection->getPreviewClasses($style, $variables['active'], $variables['toggle'], $variables['preview_type']);

  $classes = $collection->getClasses($style);
  $variables['object_attributes'] = new \Drupal\Core\Template\Attribute(['class' => $classes]);
  $variables['preview_attributes'] = new \Drupal\Core\Template\Attribute($variables['attributes']);
  $variables['preview_attributes']['class'] = array_diff($variables['attributes']['class'], $classes);
  foreach (explode(' ', $style) as $style_id) {
    $variables['preview_attributes']['class'][] = 'styles--preview--' . $style_id;
  }
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function styles_theme_suggestions_styles_preview(array $variables) {
  $suggestions = [];
  /** @var \Drupal\styles\StylesManager $stylesManager */
  $stylesManager = \Drupal::service('styles.manager');
  $collection = $stylesManager->getCollection($variables['elements']['#collection']);
  $preview_type = $variables['elements']['#preview_type'] ?? $collection->getPreviewStyle();
  if (!empty($preview_type)) {
    $suggestions[] = 'styles_preview__' . $preview_type;
  }
  return $suggestions;
}

/**
 * @param \Drupal\Core\Field\FieldItemListInterface $items Entity field
 *
 * @return string[]
 */
function styles_get_classes(FieldItemListInterface $items) {
  /** @var \Drupal\styles\StylesManager $styleManager */
  $styleManager = \Drupal::service('styles.manager');
  return $styleManager->extractClasses($items);
}

/**
 * @param \Drupal\Core\Field\FieldItemListInterface $items Entity field
 *
 * @return \Drupal\Core\Template\Attribute
 */
function styles_get_attribute(FieldItemListInterface $items) {
  /** @var \Drupal\styles\StylesManager $styleManager */
  $styleManager = \Drupal::service('styles.manager');
  return new \Drupal\Core\Template\Attribute(['class' => $styleManager->extractClasses($items)]);
}

/**
 * @param \Drupal\Core\Field\FieldItemListInterface $items Entity field
 * @param array $build Render array to apply to
 */
function styles_apply_libraries(FieldItemListInterface $items, array &$build) {
  /** @var \Drupal\styles\StylesManager $styleManager */
  $styleManager = \Drupal::service('styles.manager');
  $collection = $styleManager->getCollection($items->getFieldDefinition()->getSetting('collection'));
  $build['#attached']['library'] = array_merge($build['#attached']['library'] ?? [], $collection->getLibraries());
}

/**
 * @param \Drupal\Core\Field\FieldItemListInterface $items Entity field
 * @param array $build Render array to apply to
 */
function styles_apply_to(FieldItemListInterface $items, array &$build) {
  /** @var \Drupal\styles\StylesManager $styleManager */
  $styleManager = \Drupal::service('styles.manager');
  $collection = $styleManager->getCollection($items->getFieldDefinition()->getSetting('collection'));
  $build['#attached']['library'] = array_merge($build['#attached']['library'] ?? [], $collection->getLibraries());
  $build['#attributes']['class'] = array_merge($build['#attributes']['class'] ?? [], $styleManager->extractClasses($items));
}
