<?php

/**
 * Implements hook_locale_translation_projects_alter().
 */
function styles_locale_translation_projects_alter(&$projects) {
  /** @var \Drupal\Core\Extension\ModuleHandlerInterface $module_handler */
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('styles')->getPath();
  $projects['styles']['info']['interface translation server pattern']
    = $path . '/translations/%language.po';
}

/**
 * Implements hook_rebuild().
 */
function styles_rebuild() {
  /** @var \Drupal\styles\StylesManager $stylesManager */
  $stylesManager = \Drupal::service('styles.manager');
  $stylesManager->rebuild();
}
