<?php

use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK().
 */
function styles_example_preprocess_node(&$variables) {
  /** @var Node $node */
  $node = $variables['node'];
  if ($node->bundle() == 'style_test') {
    /** @var \Drupal\styles\StylesManager $styleManager */
    $styleManager = \Drupal::service('styles.manager');
    $classes = array_merge($styleManager->extractClasses($node->get('field_box_style')), $styleManager->extractClasses($node->get('field_background')));
    $variables['box_attributes'] = new \Drupal\Core\Template\Attribute(['class' => $classes]);
    $variables['text_attributes'] = styles_get_attribute($node->get('field_text_style'));
    $variables['content_attributes']['class'] = $styleManager->extractClasses($node->get('field_color_theme'));
    $variables['content_attributes']['class'][] = 'container';
    $variables['content_attributes']['class'][] = 'style-test';
    styles_apply_libraries($node->get('field_color_theme'), $variables);
    styles_apply_libraries($node->get('field_box_style'), $variables);
    styles_apply_libraries($node->get('field_background'), $variables);
    styles_apply_libraries($node->get('field_text_style'), $variables);
  }
}
