<?php

use Drupal\node\Entity\Node;

/**
 * Implements hook_preprocess_HOOK().
 */
function styles_example_preprocess_node(&$variables) {
  /** @var Node $node */
  $node = $variables['node'];
  if ($node->bundle() == 'style_test') {
    $variables['box_attributes'] = styles_get_attribute($node->get('field_background'));
    $variables['text_attributes'] = styles_get_attribute($node->get('field_text_style'));
  }
}
